export enum BuildingType {
  CASTLE = "castle",
  CASTLE2 = "castle2",
  CASTLE3 = "castle3",
  HOUSE = "house",
  HOUSE2 = "house2",
  HOUSE3 = "house3",
  FARM = "farm",
  FARM2 = "farm2",
  FARM3 = "farm3",
  MINE = "mine",
  MINE2 = "mine2",
  MINE3 = "mine3",
  BLACKSMITH = "blacksmith",
  BLACKSMITH2 = "blacksmith2",
  BLACKSMITH3 = "blacksmith3",
  BARRACKS = "barracks",
  BARRACKS2 = "barracks2",
  BARRACKS3 = "barracks3",
  CHURCH = "church",
  CHURCH2 = "church2",
  CHURCH3 = "church3",
}
