export enum BuildingType {
  CASTLE = 'castle',
  CASTLE2 = 'castle 2',
  CASTLE3 = 'castle 3',
  HOUSE = 'house',
  HOUSE2 = 'house 2',
  HOUSE3 = 'house 3',
  FARM = 'farm',
  FARM2 = 'farm 2',
  FARM3 = 'farm 3',
  MINE = 'mine',
  MINE2 = 'mine 2',
  MINE3 = 'mine 3',
  BLACKSMITH = 'blacksmith',
  BLACKSMITH2 = 'blacksmith 2',
  BLACKSMITH3 = 'blacksmith 3',
  BARRACKS = 'barracks',
  BARRACKS2 = 'barracks 2',
  BARRACKS3 = 'barracks 3',
  CHURCH = 'church',
  CHURCH2 = 'church 2',
  CHURCH3 = 'church 3',
}
