export enum BookType {
  COAL_PAPYRUS = 'coal papyrus',
  BRONZE_PAPYRUS = 'bronze papyrus',
  IRON_PAPYRUS = 'iron papyrus',
  GOLD_PAPYRUS = 'gold papyrus',
  TURQUOISE_PAPYRUS = 'turquoise papyrus',
  ZAPHIRE_PAPYRUS = 'zaphire papyrus',
  EMERALD_PAPYRUS = 'emerald papyrus',
  RUBI_PAPYRUS = 'rubi papyrus',

  COAL_PERGAMINE = 'coal pergamine',
  BRONZE_PERGAMINE = 'bronze pergamine',
  IRON_PERGAMINE = 'iron pergamine',
  GOLD_PERGAMINE = 'gold pergamine',
  TURQUOISE_PERGAMINE = 'turquoise pergamine',
  ZAPHIRE_PERGAMINE = 'zaphire pergamine',
  EMERALD_PERGAMINE = 'emerald pergamine',
  RUBI_PERGAMINE = 'rubi pergamine',

  COAL_MANUSCRIPT = 'coal manuscript',
  BRONZE_MANUSCRIPT = 'bronze manuscript',
  IRON_MANUSCRIPT = 'iron manuscript',
  GOLD_MANUSCRIPT = 'gold manuscript',
  TURQUOISE_MANUSCRIPT = 'turquoise manuscript',
  ZAPHIRE_MANUSCRIPT = 'zaphire manuscript',
  EMERALD_MANUSCRIPT = 'emerald manuscript',
  RUBI_MANUSCRIPT = 'rubi manuscript',

  COAL_TOME = 'coal tome',
  BRONZE_TOME = 'bronze tome',
  IRON_TOME = 'iron tome',
  GOLD_TOME = 'gold tome',
  TURQUOISE_TOME = 'turquoise tome',
  ZAPHIRE_TOME = 'zaphire tome',
  EMERALD_TOME = 'emerald tome',
  RUBI_TOME = 'rubi tome',

  COAL_SCRIPTURE = 'coal scripture',
  BRONZE_SCRIPTURE = 'bronze scripture',
  IRON_SCRIPTURE = 'iron scripture',
  GOLD_SCRIPTURE = 'gold scripture',
  TURQUOISE_SCRIPTURE = 'turquoise scripture',
  ZAPHIRE_SCRIPTURE = 'zaphire scripture',
  EMERALD_SCRIPTURE = 'emerald scripture',
  RUBI_SCRIPTURE = 'rubi scripture',

  COAL_GRIMOIRE = 'coal grimoire',
  BRONZE_GRIMOIRE = 'bronze grimoire',
  IRON_GRIMOIRE = 'iron grimoire',
  GOLD_GRIMOIRE = 'gold grimoire',
  TURQUOISE_GRIMOIRE = 'turquoise grimoire',
  ZAPHIRE_GRIMOIRE = 'zaphire grimoire',
  EMERALD_GRIMOIRE = 'emerald grimoire',
  RUBI_GRIMOIRE = 'rubi grimoire',

  COAL_BIBLE = 'coal bible',
  BRONZE_BIBLE = 'bronze bible',
  IRON_BIBLE = 'iron bible',
  GOLD_BIBLE = 'gold bible',
  TURQUOISE_BIBLE = 'turquoise bible',
  ZAPHIRE_BIBLE = 'zaphire bible',
  EMERALD_BIBLE = 'emerald bible',
  RUBI_BIBLE = 'rubi bible',

  COAL_CODEX = 'coal codex',
  BRONZE_CODEX = 'bronze codex',
  IRON_CODEX = 'iron codex',
  GOLD_CODEX = 'gold codex',
  TURQUOISE_CODEX = 'turquoise codex',
  ZAPHIRE_CODEX = 'zaphire codex',
  EMERALD_CODEX = 'emerald codex',
  RUBI_CODEX = 'rubi codex',
}
