import { Cost } from '../../commons';
import { ResourceType } from '../../resources';
import { BookType } from './book.types';

export const map__BookCosts: Record<BookType, Cost> = {
  [BookType.COAL_PAPYRUS]: {
    [ResourceType.COAL]: 1000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_PERGAMINE]: {
    [ResourceType.COAL]: 50000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_MANUSCRIPT]: {
    [ResourceType.COAL]: 200000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_TOME]: {
    [ResourceType.COAL]: 1000000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_SCRIPTURE]: {
    [ResourceType.COAL]: 10000000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_GRIMOIRE]: {
    [ResourceType.COAL]: 50000000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_BIBLE]: {
    [ResourceType.COAL]: 100000000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.COAL_CODEX]: {
    [ResourceType.COAL]: 500000000,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.BRONZE_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 1000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 50000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 200000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 1000000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 10000000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 50000000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 100000000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.BRONZE_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 500000000,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.IRON_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 1000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 40000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 200000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 900000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 8000000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 40000000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 90000000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.IRON_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 400000000,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.GOLD_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 800,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 30000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 100000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 700000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 3000000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 10000000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 50000000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.GOLD_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 100000000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.TURQUOISE_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 50,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 100,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 500,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 5000,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 40000,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 80000,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 100000,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.TURQUOISE_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 500000,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.ZAPHIRE_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 50,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 100,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 300,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 3000,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 10000,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 40000,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 80000,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.ZAPHIRE_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 250000,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.EMERALD_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 50,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 100,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 250,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 100,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 400,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 4000,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 8000,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.EMERALD_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 25000,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },

  [BookType.RUBI_PAPYRUS]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 10,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_PERGAMINE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 20,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_MANUSCRIPT]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 40,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_TOME]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 80,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_SCRIPTURE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 100,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_GRIMOIRE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 200,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_BIBLE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 300,
    [ResourceType.DIAMOND]: 0,
  },
  [BookType.RUBI_CODEX]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 500,
    [ResourceType.DIAMOND]: 0,
  },
};
