import { Cost } from '../../commons';
import { ResourceType } from '../../resources';
import { ToolType } from './tool.types';

export const map__ToolCosts: Record<ToolType, Cost> = {
  [ToolType.SMALL_SHOVE]: {
    [ResourceType.COAL]: 800,
    [ResourceType.BRONZE]: 600,
    [ResourceType.IRON]: 400,
    [ResourceType.GOLD]: 100,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.SMALL_PICKAXE]: {
    [ResourceType.COAL]: 1000,
    [ResourceType.BRONZE]: 1000,
    [ResourceType.IRON]: 500,
    [ResourceType.GOLD]: 500,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.SHOVE]: {
    [ResourceType.COAL]: 5000,
    [ResourceType.BRONZE]: 4000,
    [ResourceType.IRON]: 3000,
    [ResourceType.GOLD]: 2000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.AXE]: {
    [ResourceType.COAL]: 10000,
    [ResourceType.BRONZE]: 8000,
    [ResourceType.IRON]: 5000,
    [ResourceType.GOLD]: 5000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.PICKAXE]: {
    [ResourceType.COAL]: 20000,
    [ResourceType.BRONZE]: 20000,
    [ResourceType.IRON]: 10000,
    [ResourceType.GOLD]: 10000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.RAKE]: {
    [ResourceType.COAL]: 40000,
    [ResourceType.BRONZE]: 40000,
    [ResourceType.IRON]: 30000,
    [ResourceType.GOLD]: 20000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.BIG_SHOVE]: {
    [ResourceType.COAL]: 80000,
    [ResourceType.BRONZE]: 70000,
    [ResourceType.IRON]: 70000,
    [ResourceType.GOLD]: 60000,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.GOLD_SACK]: {
    [ResourceType.COAL]: 100000,
    [ResourceType.BRONZE]: 100000,
    [ResourceType.IRON]: 90000,
    [ResourceType.GOLD]: 70000,
    [ResourceType.TURQUOISE]: 1,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.TURQUOISE_SACK]: {
    [ResourceType.COAL]: 200000,
    [ResourceType.BRONZE]: 200000,
    [ResourceType.IRON]: 100000,
    [ResourceType.GOLD]: 80000,
    [ResourceType.TURQUOISE]: 5,
    [ResourceType.ZAPHIRE]: 1,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.ZAPHIRE_SACK]: {
    [ResourceType.COAL]: 400000,
    [ResourceType.BRONZE]: 300000,
    [ResourceType.IRON]: 200000,
    [ResourceType.GOLD]: 100000,
    [ResourceType.TURQUOISE]: 50,
    [ResourceType.ZAPHIRE]: 5,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.EMERALD_SACK]: {
    [ResourceType.COAL]: 600000,
    [ResourceType.BRONZE]: 300000,
    [ResourceType.IRON]: 200000,
    [ResourceType.GOLD]: 100000,
    [ResourceType.TURQUOISE]: 500,
    [ResourceType.ZAPHIRE]: 50,
    [ResourceType.EMERALD]: 1,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.RUBI_SACK]: {
    [ResourceType.COAL]: 1000000,
    [ResourceType.BRONZE]: 600000,
    [ResourceType.IRON]: 300000,
    [ResourceType.GOLD]: 200000,
    [ResourceType.TURQUOISE]: 1000,
    [ResourceType.ZAPHIRE]: 200,
    [ResourceType.EMERALD]: 10,
    [ResourceType.RUBI]: 1,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.CAULDRON]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 100,
    [ResourceType.DIAMOND]: 4,
  },
};
