import { Cost } from "../../commons";
import { ResourceType } from "../../resources";
import { ToolType } from "./tool.types";

/**
 * Multiplicators of production for each tool
 */
export const map__ToolMultiplicator: Record<ToolType, Cost> = {
  [ToolType.SMALL_SHOVE]: {
    [ResourceType.COAL]: .5,
    [ResourceType.BRONZE]: .5,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.SMALL_PICKAXE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: .5,
    [ResourceType.GOLD]: .5,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.SHOVE]: {
    [ResourceType.COAL]: 1,
    [ResourceType.BRONZE]: 1,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.AXE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 1,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.PICKAXE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 1,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.RAKE]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 2,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.BIG_SHOVE]: {
    [ResourceType.COAL]: 2,
    [ResourceType.BRONZE]: 2,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.GOLD_SACK]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 2,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.TURQUOISE_SACK]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 2,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.ZAPHIRE_SACK]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 2,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.EMERALD_SACK]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 2,
    [ResourceType.RUBI]: 0,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.RUBI_SACK]: {
    [ResourceType.COAL]: 0,
    [ResourceType.BRONZE]: 0,
    [ResourceType.IRON]: 0,
    [ResourceType.GOLD]: 0,
    [ResourceType.TURQUOISE]: 0,
    [ResourceType.ZAPHIRE]: 0,
    [ResourceType.EMERALD]: 0,
    [ResourceType.RUBI]: 2,
    [ResourceType.DIAMOND]: 0,
  },
  [ToolType.CAULDRON]: {
    [ResourceType.COAL]: 5,
    [ResourceType.BRONZE]: 5,
    [ResourceType.IRON]: 5,
    [ResourceType.GOLD]: 5,
    [ResourceType.TURQUOISE]: 5,
    [ResourceType.ZAPHIRE]: 5,
    [ResourceType.EMERALD]: 5,
    [ResourceType.RUBI]: 5,
    [ResourceType.DIAMOND]: 5,
  },
};